version: 2.1
jobs:
  build:
    docker:
        - image: gcc:6
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command:
              mkdir build
              cd build
              cmake ..
              make
