version: 2.1
jobs:
  build:
    docker:
        - image: gcc:6
    resource_class: xlarge
    steps:
      - run:
          command: "apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*"
      - run:
          command: "apt-get update && apt-get install -y gcc g++"
      - run:
          command: "apt-get update && sudo apt-get install -y cmake"
      - run:
          command: "mkdir build"
      - run:
          command: "cd build"
      - run:
          command: "cmake .."
      - run:
          command: "make"
