version: 2.1
jobs:
  build:
    docker:
        - image: gcc:6
    resource_class: xlarge
    steps:
      - run:
          command: "mkdir build"
      - run:
          command: "cd build"
      - run:
          command: "cmake .."
      - run:
          command: "make"
